### ISSUE TITLE
Set Default Password.sh Syntax Error

### ISSUE THREAD

**Issue by Rocketman-Chris** [Rocketman-Tech/BreakGlassAdmin#1]
An admin brought this issue up to me: 

There is syntax error in line 113 or at least that what the policy logs kept showing me when it would error during it trying to run.

I removed the “if” that was inside the double brackets, and then worked properly.

![image](https://user-images.githubusercontent.com/60405234/164558033-1426cdeb-8ee4-4713-b0fa-96826661f0e2.png)

Also line 99 comes back with “command not found”

However, line 99 doesn’t stop the script from working.

**Comment by Rocketman-Chris** [comment]
![image](https://user-images.githubusercontent.com/60405234/164558155-926f4943-8178-4b30-a3a6-ebd86e376517.png)

**Comment by geekquixotic** [comment]
The missing command, "debugLog" was a call to a function that wasn't copied from the main script. The double 'if' was a copy/paste error from before and is now resolved.
